data class Post(
    var id: Int = 0,
    val ownerID: Int = 0,
    val fromID: Int = 0,
    val createdBy: Int = 0,
    val date: Int = 0,
    val text: String = "text",
    val replyBy: Int = 0,
    val replyOwnerID: Int = 0,
    val friendsOnly: Boolean = false,
    val postType: String = "type",
    val signerID: Int = 0,
    val canPin: Boolean = false,
    val canDelete: Boolean = false,
    val canEdit: Boolean = false,
    val isPinned: Boolean = false,
    val markAsAbs: Boolean = false,
    val isFavourite: Boolean = false,
    val postponedID: Int = 0,
    val comments: Comments,
    val copyright: Copyright,
    val likes: Likes,
    val reposts: Reposts,
    val views: Views,
    val donut: Donut
)